# Generated by Django 4.2.11 on 2024-08-07 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('houseposts', '0002_rename_poster_housepost_user'),
        ('housepostcomments', '0002_rename_message_housepostcomment_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housepostcomment',
            name='housepost',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='housepostcomments', to='houseposts.housepost'),
        ),
    ]
