# Generated by Django 4.2.11 on 2024-08-07 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('houseposts', '0002_rename_poster_housepost_user'),
        ('househearts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='househeart',
            name='housepost',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='househearts', to='houseposts.housepost'),
        ),
    ]
