# Generated by Django 5.1 on 2024-08-11 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofiles', '0004_alter_userprofile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(default='bl9c2h1utow7uh2esydx', upload_to='profile_pics/'),
        ),
    ]
