# Generated by Django 4.2.11 on 2024-08-05 05:04

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('houseposts', '0002_rename_poster_housepost_user'),
        ('househeart', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='househeart',
            old_name='poster',
            new_name='user',
        ),
        migrations.AlterUniqueTogether(
            name='househeart',
            unique_together={('user', 'housepost')},
        ),
    ]
