# Generated by Django 4.2.11 on 2024-08-05 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('houseposts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='housepost',
            old_name='poster',
            new_name='user',
        ),
    ]
