# Generated by Django 5.1 on 2024-08-10 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houseposts', '0002_rename_poster_housepost_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housepost',
            name='house_image',
            field=models.ImageField(blank=True, default='house-placeholder-image_vgm8en', upload_to='images/'),
        ),
    ]
