# Generated by Django 5.1 on 2024-08-11 12:44

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('houseposts', '0010_alter_housepost_house_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housepost',
            name='house_image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='house_image'),
        ),
    ]
