# Generated by Django 5.1 on 2024-08-11 13:23

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('houseposts', '0011_alter_housepost_house_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housepost',
            name='house_image',
            field=cloudinary.models.CloudinaryField(default='house-placeholder-image_vgm8en', max_length=255, verbose_name='house_image'),
        ),
    ]
